name: stripe_dart_lab_example
description: >-
  The example app for experimenting with the Stripe API in the context of Dart.
author: Philippe Fanaro <philippefanaro@gmail.com>
publish_to: "none"
version: 1.0.0+1

environment:
  flutter: ">=1.17.0 <=1.25.0"
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stripe_sdk: ^4.0.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
