name: stripe_dart_lab_example
description: >-
  The example app for experimenting with the Stripe API in the context of Dart.
author: Philippe Fanaro <philippefanaro@gmail.com>
version: 0.0.1
publish_to: "none"

environment:
  flutter: ">=1.17.0 <=1.25.0"
  sdk: ">=2.11.0 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  # stripe_payment: ^1.0.9
  stripe_sdk: ^4.0.1

  stripe_dart_lab:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
