include: package:pedantic/analysis_options.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    prefer_double_quotes: true
