name: stripe_demo
description: A demo on how to use the Stripe API in Dart
author: Philippe Fanaro <philippefanaro@gmail.com
version: 0.0.1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
